#ifndef CONFIG_H_
#define CONFIG_H_

#define VERSION_STR "v2.2.0-alpha.1"

#define MAX_NUM_INPUTS 16
#define MAX_NUM_OUTPUTS 16
#define MAX_NUM_HPS 16
#define MAX_NUM_LSHELVS 16
#define MAX_NUM_PEQS 160
#define MAX_NUM_PEQBANKS 16
#define MAX_NUM_HSHELVS 16
#define MAX_NUM_LPS 16
#define MAX_NUM_PHASES 16
#define MAX_NUM_DELAYS 16
#define MAX_NUM_GAINS 16
#define MAX_NUM_CROSSOVER 16
#define MAX_NUM_FIRS 8

#define MAX_BANDS_PER_PEQBANK 10

#define NUMCHANNELNAMES (MAX_NUM_INPUTS + MAX_NUM_OUTPUTS)
#define NUMPRESETS 4

#define MAX_LENGTH_IR 4096
#define SIZE_IR_MEMORY 16384

#define MAX_NUM_PRESETS 4

#define DEBUG_PRINT (1)
#define ERROR_PRINT (1)

#endif
